name:                haskell-outrun
version:             0.2.5.0
github:              "danielpancake/haskell-outrun"
license:             BSD3
author:              "danielpancake and Leon Parepko"
maintainer:          "d.satarov@innopolis.university"
copyright:           "2022 danielpancake & Leon Parepko"

extra-source-files:
- README.md
- ChangeLog.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         OutRun clone game made in Haskell

dependencies:
- base >= 4.7 && < 5
- gloss
- gloss-juicy
- JuicyPixels
- utility-ht
- containers

library:
  source-dirs: src

executables:
  haskell-outrun:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-outrun

tests:
  haskell-outrun-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-outrun
